export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const DESCARGANDO_PRODUCTOS = "DESCARGANDO_PRODUCTOS";
export const DESCARGANDO_PRODUCTOS_EXITO = "DESCARGANDO_PRODUCTOS_EXITO";
export const DESCARGANDO_PRODUCTOS_ERROR = "DESCARGANDO_PRODUCTOS_ERROR";

export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";

export const EDITAR_PRODUCTO_OBTENER = "EDITAR_PRODUCTO_OBTENER";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTO_EXITO";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR";
